global:
    smtp_from: ''
    smtp_smarthost: ''
    smtp_auth_username: ''
    smtp_auth_identity: ''
    smtp_auth_password: ''
    smtp_require_tls: true

route:
    receiver: 'alerter'
    group_wait: 10s
    group_interval: 20s

receivers:
    - name: 'alerter'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#jirachannel'
            api_url: 'https://hooks.slack.com/services/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'
      email_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            to: 'success@simulator.amazonses.com'
            
